site_name: Kinsend.io Knowledge Base
site_url: https://docs.dev.kinsend.io/
repo_url: https://github.com/kinsend/kinsend-docs
use_directory_urls: false

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  logo: assets/images/ks-1-192x192.png

  icon:
    repo: fontawesome/brands/github

  features:
    - announce.dismiss
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
